image:
    sample:
        stat:               median
        min_depth:          5

    detect:
        algorithm:          sigma_threshold
        snr:                3

        # post-processing filters
        npixels:            7
        edge_cutoff:        null
        edge_fraction:      0.5  # maximum fractional area of source inside border region
        monolithic:         True
        roundness:          [0.5, 1.5]
        dilate:             0
        deblend:            False

        # MultiThreshold parameters
        multi_threshold:
            snr:            [10, 7, 5, 3]
            npixels:        [ 7, 5, 3]
            deblend:        [True, False]
            dilate:         auto
            edge_cutoff:    null
            max_iter:       5

        report:
            title_style:    [B, _]
            extend:         2

    register:
        survey:                     dss
        fov_stretch:                1.2

        plot:
            align:
                # plot model probability image + matched coordinates for each image
                show:       True
                color:      r
                marker:     o
                ms:         12
                mfc:        none

            clusters:
                show:               True
                centres:            True
                frames:             True
                nrs:                True
                show_bandwidth:     True
                trim_labels:        False

            mosaic:                 False


        align:
            hop:                        True
            fit_angle:                  True
            refine:                     True
            
            sigma_distance_scale:       3
            sigma_fallback:             10

        measure:
            centre:                         mean
            source_detection_threshold:     0.25
            outlier_distance:               Null
            report:                         True

        cluster:
            algorithm:              MeanShift
            
            plot:
                features:
                    s:                  25
                    marker:             '*'
                    cmap:               null
                    label:              Centroids ({} images)
                
                centres:
                    marker:             +
                    color:              k
                    ms:                 2.5
                    alpha:              1

                labels:
                    size:               8
                    emboss:
                        linewidth:      1.5
                        color:          '0.2'

                outliers:
                    color:              r
                    marker:             x
                    alpha:              0.5

                bandwidth:
                    ec:                 '0.2'
                    alpha:              0.75
                    label:              '{algorithm}(bandwidth={bandwidth:.3f})'

                frames:
                    fc:                 none
                    lw:                 1
                    ec:                 '0.5'

    mosaic:
        ref:
            cmap:           Greys
            alpha:          1

        alpha:
            min:    0.025
            cycle:  0.65

        labels:
            format: image{:i}
            color:  w

        target:
            color:            forestgreen
            arrow:
                size:             10
                head_distance:    2.5
                offset:           [0, 0]

            text:
                offset:         3
                emboss:
                    linewidth:  2
                    color:      k


    gmm:
        plot:
            image:
                grid_size:      100
                cmap:           Blues
                alpha:          0.5
            points:
                marker:         .
                color:          k
                ms:             1
                label:          'Centroids'
            peak:
                show:           False
                marker:         ''
                color:          r


    display:
        image:
            cmap:           Null  # 'cmr.voltage_r',
            hist:           False
            sliders:        False
            cbar:           False

        contours:    
            cmap:           hot
            lw:             1.5

        frame:
            fc:             none
            lw:             1
            ec:             '0.5'

        marker: 
            marker:         x
            color:          w
            ls:             none

        text: 
            size:           xx-small
            color:          w
            weight:         heavy
            offset:         5

    segments:
        display:
            contours:  
                cmap:       hot
                alpha:      1
                lw:         1.25
                emboss:     2.5

            text:  
                color:      w
                alpha:      0.5
                weight:     heavy
                va:         center
                ha:         center
                emboss:     [1, k]

            console:
                extend:     1
                cmap:       null
                contour:    [r, B]

                stats:
                    flux:       
                        header:         Flux [ADU]
                        thousands:      ' '
                    com:        
                        header:         Position (y, x) [px]
                        significant:    1
                    areas:      
                        header:         Area [px²]

                    roundness:  
                        header:         Roundness
                        significant:    3


campaign:
    pprint:
        max_lines:  25
        max_items:  100
        sep:        ' | '
        attr:       file.name

    tabulate:
        [name, target, obstype, nframes, ishape, binning]


lc:
    io:
        title:  Light Curve for {}

        # columns [name, unit, description]
        columns:
            time: 
                [bjd, day, Barycentric Julian Date]
                # [sidt, h  Sidereal time in seconds since midnight]
            counts: 
                [Flux, counts, Total integrated counts for star (background subtracted)]
            sigma:   
                [σFlux, counts, Standard deviation uncertainty on total counts]
            outlier: 
                [oflag, '', Outlier flag]

        precision:  5

phot:
    proc:
        progress:
            bar_format: >-
                {{desc}: {percentage:3.0f}%{bar}{n_fmt}/{total_fmt}:|green}
                {rate_fmt:|gold}
                {elapsed:|cyan} eta {remaining:|cyan}
            ascii: " ╸━"
            unit:  " frames"


    # source tracking
    tracking:
        # ------------------------------------------------------------------------ #
        centroids:
            # features used for tracking
            com:                            1
            # geometric_median:               1
            peak:
                upsample: 1     # note, changing this will siginificantly affect compute times
                filter: lanczos
        
        # subtract background from image prior to computing features
        pre_subtract:       True
        # statistic used for background
        bg:                 median
        
        # Required positional accuracy in pixels
        precision:          0.5
        
        # Per-source weights for frame offset calculation. Use "snr" for
        # signal-to-noise weighting.
        weights:            snr 
        

        cutoffs:
            edge:           0
            snr:            3.
            # Sources with signal-to-noise ratio less than this will not be 
            # considered when solving for image dither
            distance:       10
            # For outlier detection: maximum distance allowed for point measurements
            # from centre of distribution.
            saturation:     95
            # If we know the saturation value of the CCD chip, we discard pixels above
            # this percentage of the saturation value

        compute:
            centres: [0 , 1000, 100 ]

        filenames:
            measurements:       centroids.dat       # (n, nstats, nsources, 2)
            coords:             coords.dat          # (nsources, 2) structured ['xy', 'std']
            frame_info:         frame-info.dat      # (n, 2)        structured
            source_info:        source-info.dat     # (n, nsources) structured
            feature_weights:    feature-weights.dat # (nstats, 1, 1)
            source_weights:     source-weights.dat  # nsources  
            

        # ------------------------------------------------------------------------ #
        table:
            title:          Measured source coordinates
            title_style: 
                fg:         [B,  _,  w]
                bg:         darkslategrey
            col_head_style:
                fg:         [B,  _,  black]
                bg:         grey
            col_head_align: ^ 
            precision:      3
            align:          r
            row_nrs:        True
            max_rows:       25

        # ------------------------------------------------------------------------ #
        video:
            figsize:          [8, 8]
            subplot_kws:
                top:        1.0
                bottom:     0.02
                left:       0.125
                right:      0.9
            
            legend:
                show:           on
                show_weights:   on
            
            features:
                cmap:       rainbow
                emboss:     1.5

            clim_every:     0

        # ------------------------------------------------------------------------ #
        plots:
            centroids:
                com:              [r, +, "Centre of Mass"]
                peak:             [m, ^, "Peak"]
                # marginals:        [orange, '.', "Marginal Gaussian MLE"]
                avg:              [k, x, "Weighted Centroid"] 
                # NOTE: avg sould be last

            labels:
                offset: [6, 6]
                color:  w
                size:   10 # x-small
                alpha:     1
                # fontweight:bold

            position:
                figsize:            [12, 6.5]
                legend:             False
                show:               [avg, weights, caption]  #  nulls, pixel

                density:
                    cmap:               null
                    tessellation:       hex
                    min_count:          3

                scatter:
                    marker: x
                    s:      5
                    ls:     ''
                    color:  null
                    zorder: 1
                    alpha:  0.35
                
                title:
                    size:       13
                    fontweight: bold
                    pad:        10

                caption:
                    pos:    [0.075, 0.01]
                    text:   >-
                        $x_0 = {x:s}$;
                        $y_0 = {y:s}$
                    va:     bottom
                    ha:     left
                    bbox:       # these are matplotlib.patch.Patch properties
                        boxstyle:    round
                        facecolor:  lightgrey

                cbar:
                    # shrink: 0.9
                    pad:     0.01
                    label0:  Counts
                    label1:  Counts (Recentred)

                pixel: 
                    lw:         0.75
                    ls:         '--'
                    fc:         none
                    ec:         lime
                    zorder:     100

                precision:
                    lw:         0.75
                    ls:         '--'
                    fc:         none
                    ec:         darkgreen
                    zorder:     100