
# source tracking
tracking:
    filenames:
        measurements: centroids.dat
        measure_avg:  centroids-mean.dat
        measure_std:  centroids-std.dat
        delta_xy:     coords-delta.dat
        sigma_xy:     coords-std.dat
        flux:         flux.dat
        flux_std:     flux-std.dat
        snr:          snr.dat
        _origins:     origin.dat

    table:
        txt:    bold
        bg:     g

    progress:
        bar_format: >-
            {{desc}: {percentage:3.0f}%{bar}{n_fmt}/{total_fmt}:|green}
            {rate_fmt:|gold}
            {elapsed:|cyan} eta {remaining:|cyan}
        ascii: " ╸━"
        unit: frames

    plots:
        centroids:
            com:              [r, +, Centre of Mass]
            com_bg:           [r, x, CoM (bg sub)]
            geometric_median: [g, o, Geometric Median]
            peak:             [m, ^, Maximum]
            avg:              [k, x, Weighted Average]  # NOTE: sould be last

        labels:
            offset: [6, 6]
            color:  w
            size:   10
            # fontweight:bold

        position:
            density:
                cmap:               null
                tessellation:       hex
                min_count:          7

            scatter:
                marker: x
                ls:     ''
                color:  null
                # mfc:    none
                zorder: 1
                alpha:  0.35

            legend:             True
            show:               [avg, weights]  #  nulls
            figsize:            [7.5, 7]


            pixel: 
                lw:         1
                ls:         --
                fc:         none
                ec:         lime
                zorder:     100



        

        # upsample_max:     (d Upsampled Max
        # com_bg:           (+ Centre of Mass (Median sub

