
# source tracking
tracking:
    centroids:
        com:                0
        com_bg:             1  # use if data not calibrated / background subbed
        geometric_median:   0
        peak:               1
        # 'upsample_max':     0

    precision:          0.5
    # Required positional accuracy in pixels
    weights:            snr 
    # Per-source weights for frame offset calculation. Use "snr" for
    # signal-to-noise weighting.

    cutoffs:
        edge:           0
        snr:            3.
        # Sources with signal-to-noise ratio less than this will not be 
        # considered when solving for image dither
        distance:       10
        # For outlier detection: maximum distance allowed for point measurements
        # from centre of distribution.
        saturation:     95
        # If we know the saturation value of the CCD chip, we discard source
        # measurements with saturated pixels.

    compute:
        weights: [0 , 1000, 25  ]
        centres: [0 , 1000, 100 ]

    filenames:
        measurements:   centroids.dat
        measure_avg:    centroids-avg.dat
        measure_std:    centroids-std.dat
        delta_xy:       coords-delta.dat
        sigma_xy:       coords-std.dat
        flux:           flux.dat
        snr:            snr.dat
        _origins:       origin.dat

    table:
        title:          Measured source coordinates
        title_style: 
            fg:         [B,  _,  w]
            bg:         darkslategrey
        col_head_style:
            fg:         [B,  _,  k]
            bg:         grey
        col_head_align: ^ 
        precision:      3
        align:          r
        row_nrs:        True
        max_rows:       25


    progress:
        bar_format: >-
            {{desc}: {percentage:3.0f}%{bar}{n_fmt}/{total_fmt}:|green}
            {rate_fmt:|gold}
            {elapsed:|cyan} eta {remaining:|cyan}
        ascii: " ╸━"
        unit:  " frames"

    plots:
        centroids:
            com:              [r, +, Centre of Mass]
            com_bg:           [r, x, CoM (bg sub)]
            geometric_median: [g, o, Geometric Median]
            peak:             [m, ^, Maximum]
            # upsample_max:     (d Upsampled Max
            avg:              [k, x, Weighted Average]  # NOTE: sould be last

        labels:
            offset: [6, 6]
            color:  w
            size:   10
            # fontweight:bold

        position:
            density:
                cmap:               null
                tessellation:       hex
                min_count:          7

            scatter:
                marker: x
                ls:     ''
                color:  null
                # mfc:    none
                zorder: 1
                alpha:  0.35

            legend:             False
            show:               [avg, weights]  #  nulls
            figsize:            [5, 8]
            
            cbar:
                # shrink: 0.9
                pad:    0.025


            pixel: 
                lw:         1
                ls:         --
                fc:         none
                ec:         lime
                zorder:     100
